# Test to verify gtest works
cc_test(
    name = "meta_test",
    srcs = ["meta_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = ["@gtest//:gtest"],
)

cc_test(
    name = "bool_test",
    srcs = ["meta_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = ["@gtest//:gtest"],
)
